name: build

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        luaVersion: ["5.1", "5.2", "5.3", "5.4", "luajit"]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@master

    - uses: leafo/gh-actions-lua@master
      with:
        luaVersion: ${{ matrix.luaVersion }}

    - uses: leafo/gh-actions-luarocks@master

    - name: setup-linux
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get install jackd libjack0 libjack-dev

    - name: setup 
      run: |
        luarocks --server=https://luarocks.org/dev install nocurses
        luarocks --server=https://luarocks.org/dev install carray
        luarocks --server=https://luarocks.org/dev install mtmsg
        luarocks --server=https://luarocks.org/dev install auproc

    - name: build
      run: |
        set -e
        lua -v
        luarocks make rockspecs/ljack-scm-0.rockspec
        lua -e 'print(require"ljack"); print(require"ljack"._VERSION)'

    - name: test
      run: |
        set -e
        lua -v
        jackd -r -ddummy -r44100 -p1024 &
        lua examples/example01.lua
     